# Abstract

New teachers face numerous challenges during their transition from teacher preparation programs into professional employment contexts. With many more opportunities for professional learning available today, new teachers must navigate an increased number of potentially conflicting messages about what and how to teach. This study explores the support systems that new teachers construct during induction and how they use social media for this purpose. These systems can be understood as *professional learning networks* (PLNs) consisting of tools, people, and spaces and useful for improving teaching and learning. Interviews with new teachers provide evidence of reasons why they develop PLNs as well as what tools, people, and spaces they include in these support systems. Findings demonstrate that new teachers construct induction support systems to navigate change, scarcity of resources, and conflicting teaching beliefs. New teachers look for tools for planning, enacting practice in the classroom, and connecting socially. People in new teachers’ PLNs included both in-school and out-of-school connections. Interviewees described how they use various social media platforms in their induction support systems as well as boundaries they maintain around social media use. Finally, new teachers described their engagement on social media in terms of browsing, asking, and exchanging. Implications of these findings are discussed for new teachers, teacher educators, and education leaders—especially regarding how stakeholders can help alleviate induction pressures on new teachers. This study contributes insight into the convergence of tensions experienced by new teachers as they consider whether and how to construct support systems during induction, including if and how to look for help on social media.

## Keywords

teacher induction, professional learning network, learning ecology, agency, teacher professional development, social media
