# Introduction

Early career teachers face numerous challenges during their transition from teacher preparation programs into professional employment contexts (i.e., their *induction* period). At minimum, early career teachers must move from learning about teaching to actually practicing teaching. The difficulties of this transition may be compounded when early career teachers enter their school of employment with notions of teaching that are not shared &mdash; or in some instances, are even actively discouraged &mdash; by more experienced colleagues. The literature has characterized this tension as a “two worlds pitfall” (Feiman-Nemser & Buchmann, 1985) resulting from conflicting messages from the academic “world” of the teacher preparation program and the practical “world” of the professional teaching context. Furthermore, it seems likely that tensions have only increased as people and information have become more connected through digital technologies. Social media platforms, in particular, have created new opportunities for teachers’ ongoing professional learning (Trust & Prestridge, 2021). As a result, early career teachers must navigate an increased number of potentially conflicting messages about what and how to teach.

The purpose of this study is to explore the support systems that early career teachers construct during induction and how they use social media for this purpose. These support systems can be understood as *professional learning networks* (PLNs) consisting of tools, people, and spaces useful for improving teaching and learning (Krutka et al., 2017; Trust et al., 2016; Trust & Prestridge, 2021). Teachers connect to &mdash; and make connections between &mdash; various sources of information, resources, and encouragement to build their own PLN. For the purposes of this study, I define a PLN as a support system of interconnected tools, resources, people, and spaces &mdash; spanning local and online contexts &mdash; with the teacher at the center.

An early career teacher develops their support system (i.e., PLN) from a subset of all possible tools, people, and spaces available, because no one can learn with all tools from all people in all spaces. For instance, a recent count showed that there are more than 900 distinct education-related Twitter hashtags (Participate Inc., 2019), which organize spaces for ongoing conversations about teaching and learning (Greenhalgh et al. 2020). These are spaces on just one social media platform; there are many more, including 16 distinct, teaching-related discussion forums comprising the Reddit Education Network (Staudt Willet & Carpenter, 2020, 2021), many teacher Facebook groups, Instagram hashtags, and so on. Innumerable people participate in these many spaces, sharing tools that might provide useful support to teachers.

There is a gap in how the literature has covered early career teachers’ challenges and support systems. Research on teacher induction has primarily focused on support systems of tools, people, and spaces that exist within formal programs. This body of work has not fully considered implications of recent technological advancements that may create more expansive opportunities for &mdash; and new complications of &mdash; early career teachers’ support systems. Meanwhile, research on teachers’ use of social media has rarely taken into account the specific needs of early career teachers as they transition into teaching.

This study addresses the gap in the literature by specifically addressing both induction challenges and social media practices of early career teachers. This work is able to then contribute recommendations to teacher educators and education leaders regarding how to sustain early career teachers in the profession. These insights are important because even prior to the disruptions of the COVID-19 pandemic in 2020, teachers had been leaving the classroom at an unprecedented rate (Carver-Thomas & Darling-Hammond, 2017; Hackman & Morath, 2018), with especially high attrition among early career teachers (Ronfeldt & McQueen, 2017). Induction challenges continue to grow, and early career teachers’ ability to develop and sustain robust PLNs (i.e., supports systems) must expand as well. 
