# Purpose and Research Questions

The purpose of this study is to explore the support systems that early career teachers construct during induction and how they use social media for this purpose. Framed with PLN components of tools, people, and spaces, the review of literature showed that more is known about early career teachers’ support systems with regard to formal tools, in-school people, and local spaces. Less is known about early career teachers’ experiences and challenges as they intersect with informal tools, out-of-school people, and social media spaces. This gap prompts four research questions:

- **RQ1.** What reasons, if any, do early career teachers report for constructing support systems during induction?
-	**RQ2.** What tools for professional learning, if any, are early career teachers seeking when constructing support systems during induction?
-	**RQ3.** With whom do early career teachers connect when constructing support systems during induction?
-	**RQ4.** How, if at all, do early career teachers use social media platforms to expand the tools, people, and spaces available when constructing support systems during induction?
