# Discussion

In this study, I address a gap in the literature related to early career teachers’ induction challenges and support systems, specifically, exploring the specific needs of early career teachers as well as the expanded range of tools, people, and spaces available through social media. Some themes reported in the findings were consistent across all interviewees, whereas other themes varied by participant. I discuss how results demonstrated both consistency and variance in the following paragraphs, and I connect these interpretations to the literature.

## Consistency of Results

I found a number of themes to be present across all nine interviews. Each early career teacher I interviewed sought tools for planning, enacting practice, and connecting socially. They found these tools through people both within their schools and beyond. All of them engaged on social media by browsing, and they all had made choices about keeping personal and professional parts of their lives separate on social media.

The most striking point of consistency across all interviewees was how they enacted identity-agency. As defined in the Framework section, identity-agency means taking responsibility for and actively investing in one’s own self-development as a teacher (Ruohotie-Lyhty & Moate, 2016), starting by recognizing a challenge, forming a strategy to overcome that challenge, and then implementing the strategy (Bandura, 2001). In the present study, it was evident that each of the early career teachers enacted identity-agency when making decisions regarding if and how to construct their induction support system. Interviewees consistently described a purposeful sense of having a job to do and a determination to find the tools, people, and spaces necessary to do that job well. For instance, Julie, Taylor, and others were enacting identity-agency when they realized they were missing teaching resources and went to specific social media platforms to find what they needed. Anne enacted identity-agency by venting in appropriate social media spaces as an outlet for the frustrations accumulated from teaching under challenging conditions. Simone enacted identity-agency by seeking broader perspectives on social media.

Interviewees also exercised agency when they chose *not* to pursue some of the opportunities available to them. On one hand, social media provide just-in-time professional development (Greenhalgh & Koehler, 2017) and access to expertise beyond a teacher’s local school (Beach, 2017). However, these affordances came with a cost, as early career teachers described feeling pressure to be constantly available with little distinction between professional and personal contexts (Fox & Bird, 2017). In this study, each interviewee perceived benefits of expanding induction support systems through social media, but they were all also mindful of preserving personal-professional boundaries, echoing the sentiments of other teachers in past research (e.g., Trust & Prestridge, 2021). These practices match the self-reflection and self-awareness that Fox and Bird (2017) argued are necessary for teachers to exert control (i.e., exercise agency) over how and how much they connect with others through social media. In these instances, declining to pursue some opportunities meant that the early career teacher would have more time and energy to actively invest in their self-development elsewhere.

The consistency in this subset of results may be related to the ways that participants in the present study were similar. Significantly, they were all early career teachers pursuing graduate degrees. This shared background may suggest common professional goals (Trust & Prestridge, 2021) related to the improvement of planning, enacting practice in the classroom, and connecting socially. In addition, participants likely also shared professional limitations in the form of confidence and time (Trust & Prestridge, 2021), which for early career teachers would be low and limited, respectively. These factors may connect to interviewees’ shared social media behavior of engaging in the least demanding way (i.e., browsing) and trying to keep personal and professional spheres separate.

These consistent themes across interviewees connect to and extend the literature on teacher networks. For instance, Bartell et al. (2019) described how early career teachers “weave interconnected webs of professional relationships based upon their needs” (p. 303) that may include social media conversations. März and Kelchtermans (2020) found that early career teachers’ support systems extended beyond the mentor-mentee relationship to also incorporate “school-external networks” (p. 8) that included educational advisors, former teacher educators, and classmates from their teacher education. In the present study, findings demonstrate that early career teachers’ webs of relationships include the two worlds of the teacher preparation program and the school of employment (Feiman-Nemser & Buchmann, 1985; Horn et al., 2008; März & Kelchtermans, 2020; Thompson et al., 2013) but are more complicated still. Here, early career teachers also described supportive phone calls with family and friends, membership in teacher organizations, and social media use.

## Variance of Results

In addition to consistent themes, results also demonstrated several themes that varied between interviewees. To start, there were differences in the underlying reasons why early career teachers constructed induction support systems. Interviewees experienced change, scarcity of resources, and conflicting beliefs quite differently. Early career teachers also reported varying degrees of social media engagement in terms of asking and exchanging, and the purposes for which they used various social media platforms differed as well. Finally, several participants described their need to maintain boundaries around social media use for the sake of time management or social comparison, but this sentiment was not shared by all.

An agentic perspective on PLNs, which foregrounds the early career teachers’ responsibility for ensuring their support system meets their needs, provides insight into the variance of results. The results here follow Tao and Gao’s (2017) finding that teachers were consistent in making agentic choices for their professional development but varied in the specifics of their agentic actions. In this study, all interviewees described enacting identity-agency, but *how* they did so differed.

Differences in teachers’ backgrounds may explain some differences in how they construct support systems (Wray & Richmond, 2018), but not all. For instance, only three interviewees (Hallie, Mike, and Simone) reported time management around social media use as being important to them. Hallie and Mike came from extremely well-resourced suburban public schools, whereas Simone’s school was under-resourced. The enactment of identity-agency in these examples does not seem to be entirely explained by a teacher’s context; this is similar to Ruohotie-Lyhty and Moate’s (2016) observation that preservice teachers were already investing in self-development even prior to entering into a professional teaching context. This seems to reinforce that PLNs are complex systems, and that dichotomies are insufficient for understanding them (Trust & Prestridge, 2021).

Considering agency as “the result of an accumulation of perceived positive outcomes” (Bartell et al., 2019, p. 302) may offer further insight. For instance, Simone’s sense of identity-agency was strengthened by the affirmation she received in response to giving advice in a teacher Facebook group. In the language of Trust and Prestridge’s (2021) model, there was a confluence of space dynamics, relationships, and confidence that helped Simone feel positive about her past engagement in the Facebook group and more likely to give advice again in that space. This may suggest that early career teachers’ decisions to construct and expand their induction support systems are related to both contextual factors (i.e., ecology) and experiences (i.e., identity-agency).

Finally, identity-agency is also likely related to how some early career teachers navigated conflicting beliefs about teaching. Nearly half of interviewees described ways they experienced their beliefs about teaching and learning conflicting with those held by new colleagues in their schools. Sometimes the process of reconciling differences was as straightforward as pausing for self-reflection in the midst of recognizing conflicting teaching beliefs from preparation programs and schools of employment (i.e., the two worlds pitfall; Feiman-Nemser & Buchmann, 1985; Horn et al., 2008), but other times the tensions were more complex. This is similar to Vaughn’s (2013) findings of in-service teachers experiencing cognitive dissonance while attempting to align their instructional practice with their vision of teaching (i.e., enacting agency). For instance, Julie had to think carefully about how to go against her principal’s expectations for student discipline, and Hallie had to decide how much to push her colleagues to incorporate more anti-racism curricular materials. These examples illustrate how early career teachers must choose the degree of conflict they are willing to have with colleagues around issues where educational thinking has changed in recent years. That is, variance in this theme is related not just to the presence of differing opinions, but also to early career teachers’ capacity for and willingness to enact agency in these areas.

The variance of themes in a subset of findings reinforces that teaching is complicated by contextual realities and challenges &mdash; and that these complications are experienced differently by different study participants (Trust & Prestridge, 2021). Interviewees had different experiences as they entered the teaching profession, with varying degrees of resource availability and disruptions related to change. Some interviewees navigated changes related to new curriculum, staff transitions, and shifts in classroom assignments. In response to such changes, early career teachers sometimes adapted how they constructed their induction support systems, including how they used social media (Carpenter et al., 2021; Veletsianos et al., 2019).

Understanding the variance of results may be aided by the ecological perspective on PLNs, which highlights that these support systems are composed of interconnected and mutually influential spaces: a learning ecology (Barron, 2006). The cumulative support system of tools, people, and spaces looked different for each interviewee (Trust & Prestridge, 2021). Although no single piece of a PLN is likely to meet all their needs, early career teachers in this study were able to construct a holistic support system that collectively helps them overcome induction challenges, reflecting Stevenson et al.’s (2019) findings. Early career teachers often looked in informal spaces for tools and people to expand their supports systems, including the in-school teachers lounge, phone calls with friends and family, and numerous social media platforms. These informal networks complemented and influenced formal professional learning and practice, similar to Peters and Romero’s (2019) observations.
