# Implications

Jointly holding ecological and agentic perspectives on new teachers’ PLNs (i.e., their support systems) highlights a tension: the availability of more tools, people, and spaces also means increased demands on time and agency. Options available today far outnumber the two worlds identified by Feiman-Nemser and Buchmann (1985), as interviewees in this current study demonstrated. As the complexity of a new teachers’ support systems increases (Trust & Prestridge, 2021), the amount of agency required to seek induction supports seems to increase as well. Putnam and Borko (2000) voiced this argument two decades ago: new kinds of teacher learning communities offer new opportunities for improving educational practice, but they also introduce new tensions.

This study contributes new categories to the literature by exploring the support systems that new teachers construct during induction and how they use social media for this purpose. In the following paragraphs, I describe implications of these findings for new teachers, teacher educators, and education leaders—especially regarding how stakeholders can help relieve induction pressures from new teachers. Finally, implications for researchers are discussed, naming limitations of the current study as well as directions for future work.

## Implications for New Teachers

New teachers in this study described how they grappled with issues related to the way social media platforms merge multiple contexts and bring together audiences that would normally be distinct—that is, *context collapse* (Marwick & boyd, 2011). In addition, interviewees talked about how they struggle to manage expectations to be being constantly available to students and parents, reflecting themes from past research (Fox & Bird, 2017). A consequence of context collapse and assumptions of availability is that new teachers must constantly think about their audience on social media; they are never sure whether their students, or parents of their students, are paying attention to their social media activity. Numerous interviewees expressed a desire to be free from such scrutiny, and their solution was to be less active on social media or to choose more private spaces, such as teacher Facebook groups. These findings are consistent with past work such as Burkell et al.’s (2014) study that showed Facebook users participated with an understanding that Facebook is a public and visible space, part of a broader system of *networked publics* on social media (boyd, 2007).

A related issue is new teachers’ struggle with social comparison. For instance, Anne wanted to use social media to vent to about the difficult circumstances in her under-resourced school and find needed materials, but context collapse through Instagram meant she was also seeing cute classroom designs from teachers in wealthy suburban districts. Rather than finding relief, Anne was exasperated by the passive, indirect reminders that other teachers possessed the resources, time, and inclination to elaborately decorate their classrooms. These experiences demonstrate how social media may elicit more feelings of competition than collaboration (Lantz-Andersson et al., 2018), leaving Anne to feel like “a crappy teacher.” Participants in Carpenter et al.’s (2020) study made similar comments, reporting how using Instagram raised unrealistic expectations for themselves and made them feel like they were stuck in a “comparison spiral” (p. 9). Vogel et al.’s (2014) Facebook study also demonstrated negative effects of “upward” social comparison stemming from comparing oneself to a healthy-appearing or high-activity user. To minimize negative effects of comparison on social media, new teachers may find better support through locally hosted (i.e., school- or district-sponsored) learning management system shells similar to the one organized by Wallace’s school in Google Classroom. Reddit’s anonymity may also be useful, as research has shown lower levels of performative and self-promotional content in teaching-related subreddits than in some other social media spaces (Staudt Willet & Carpenter, 2021).

## Implications for Teacher Educators and Education Leaders

A goal for teacher educators and education leaders should be *sustaining* new teachers by attending to their lived experiences, not just *retaining* them (Clandinin et al., 2015). This does not necessarily mean removing all tensions, because conflicts may prompt further development of pedagogical reasoning, adaptability, and skills for contextualization (Horn et al., 2008). However, the degree of difficulty should be scaffolded so that new teachers are not overwhelmed.

One way to sustain new teachers is by expanding notions of what “counts” for professional development. Informal, self-directed learning opportunities through social media should be taken seriously as a complement to formal induction programs already offered by schools and districts. Despite the pervasiveness of the “digital native” myth in education, education leaders should not assume that new teachers will want or know how to construct informal, self-directed additions to their induction support systems through social media. Indeed, one of Trust and Prestridge’s (2021) conclusions was that such self-directed learning can “limit how and what educators learn and the potential impact of their PLN on their professional growth” (p. 9). Therefore, new teachers benefit from guidance, encouragement to explore, and time to try. At minimum, schools and districts should have a clear, positively framed (i.e., not just a list of “Do Not” statements) social media policy. Schools and districts may also wish to establish some password-protected online spaces (e.g., platforms for sharing resources and ideas for lesson plans) as initial offerings toward expanding new teachers’ induction support systems. The PLN discussion forums hosted by the International Society for Technology in Education (https://iste.org/learn/about-iste-plns) may provide a useful model to follow.

Although it may be tempting to consider high frequency and self-promotional forms of social media use as ideals, new teachers should not be held to such standards. Past research has often reported *participation inequality* wherein a small number of participants contribute almost all social media content (e.g., Nielson, 2006; Staudt Willet, 2019). Other research has unpacked the activity of “celebrity” educators on social media, so-called *teacherpreneurs* (Shelton & Archambault, 2019) and documented extensive self-promotional behavior by educators on social media (Prestridge, 2019; Staudt Willet, 2019). However, such high-profile cases are not necessarily the norm or even desirable. Carpenter and Harvey (2019) found that some educators had negative feelings about seeing this sort of content, “feeling conflicted, frustrated, or exasperated about various kinds of posts from other educators” (p. 5). In this study, new teachers were highly pragmatic, aware of their time and expertise constraints—a theme also reflected by Trust and Prestridge’s (2021) findings. Interviewees were motivated to get the supports they needed to perform their teaching duties, and they rarely acted as “self-seeking contributors” or “info-networkers” (Prestridge, 2019) who actively tried to garner attention from or pass information along to others.

A far more common form of social media participation is *lurking*—that is, being present and watching but not making oneself known by contributing. Edelmann (2013) argued that lurking could be better characterized as *observing*, a term with less negative connotations and an acknowledgement that lurkers are actively reading and paying attention—and may even be sharing in other contexts. Bozkurt et al. (2020) reframed lurking as a form of *legitimate peripheral participation* in a community of practice (Lave & Wenger, 1991). That is, merely observing and retrieving resources are valid uses of social media, especially for new teachers who feel the limitations of time and agency. For instance, new teachers like Wallace should not feel like they need to apologize for being a “taker” on social media. Rather, they should understand that observational forms of participation are appropriate for this stage of their professional journey and observing may be a useful onramp for developing the confidence to interact in online spaces (Bozkurt et al., 2020; Trust & Prestridge, 2021).

Teacher educators and education leaders should take an active approach to alleviate any pressure new teachers may experience to actively contribute on social media. Stakeholders should offer a clear social media policy and talk through possibilities and expectations for expanding and supporting the self-directed elements of new teachers’ induction support systems. They could also make specific suggestions to reduce performative inclinations, such as participating anonymously in teaching-related subreddits (Staudt Willet & Carpenter, 2020, 2021) or subscribing to summary emails from social media platforms, as Mike did with Pinterest.

## Implications for Researchers

The qualitative design of this study does not produce generalizable results, which raises several limitations—and possibilities for future work—that should be of interest to researchers. A first issue is that the nine new teachers I interviewed did not reflect the full diversity of U.S. teachers. Interviewees were mostly white and mostly women, and although these characteristics do follow national trends (National Center for Education Statistics, 2020), future researchers may wish to explore the induction experiences and social media use of new teachers with minoritized identities. For instance, a future study should explore the specific induction challenges of Black teachers, particularly given the increased support for anti-racism education beginning in Summer 2020. In addition, all participants in this study were enrolled in a Master’s program in education, and there may be some confounding effects around the agency required to enroll in grad school during one’s first few years as a teacher and the agency needed to expand induction support systems. Future work should include new teachers who are not pursuing an advanced degree. 

A second issue is that this study only described teachers’ reflections at one point in time. Furthermore, interviews were conducted in February 2020, a month prior to when COVID-19 disruptions radically altered the landscape of U.S. education. Collecting additional data, such as new teachers’ challenges and social media use during and after the COVID-19 pandemic, would be useful for comparison to the findings reported in the present study. Approaches like diary and experience sampling methods (e.g., Bolger & Laurenceau, 2013) in future work would provide alternative methods for collecting self-reported data that may be better for capturing in-the-moment descriptions of induction challenges and support systems.

A third limitation is that this study’s findings cannot speak to wide-scale trends in induction challenges and new teachers’ social media use. However, results have established a codebook (Appendix E) and categories of social media use (Table 5) that can be investigated further with computational and quantitative approaches to investigate broad trends. Findings also suggest types of social media data to collect and a priori codes that can be applied in hand-coded content analysis or machine learning classification. 
