# Conclusion

Passion alone is not enough to sustain teaching careers. Induction challenges have real effects on early career teachers, who may feel like they are in survival mode (Thompson et al., 2013; Zhukova, 2018), left to “sink or swim” in the isolation of their own classrooms and educational contexts (Ingersoll, 2012). Early career teachers take initiative to construct induction support systems, but if their identity-agency is fully spent, they may still find they have little choice but to leave the profession. This can fill teachers with intense emotion and regret, still committed to the needs of students but unable to continue (Dunn, 2018). Teacher departures have high costs to districts, schools, and students. School districts pay a financial price: more than $20,000 to replace each teacher who leaves (Carver-Thomas & Darling-Hammond, 2017). More importantly, educator turnover has been found to negatively affect students, such as by reducing learner achievement (Carver-Thomas & Darling-Hammond, 2017; Ronfeldt et al., 2013).

Teacher learning is no longer confined to the traditionally conceived two worlds of teacher preparation programs and PK-12 schools. Social media continue to expand the number of available tools, people, and spaces useful for professional learning. Early career teachers, teacher educators, and education leaders must likewise continue to expand their understanding of how these different pieces fit together to form an effective support system (i.e., PLN). Simultaneously, the costs to early career teachers’ agency, especially as support systems become more complex, must not be overlooked or under-estimated.

Ultimately, many early career teachers would likely echo Julie’s sentiment about constructing her induction support system: “I feel like I filled a lot of gaps.” This study contributes new understanding of how and why early career teachers are taking these extra steps in self-directed learning.
