# Appendices {.unnumbered}

## Appendix A: Publicity Email {.unnumbered}

**Subject:** *Recruiting Participants: Dissertation Study about the Experiences of New Educators*

Hello! I am an MAET alumnus (graduated in 2015) and current doctoral student at MSU. My doctoral dissertation study focuses on the experiences of new educators, so I am looking for MAET students who have fewer than three years of experience as educators, whether as K12 classroom teachers or in other roles. 

I am inviting you to participate in one interview of 45-60 minutes on Zoom. I will ask you about your experiences as a new educator—specifically, any struggles or challenges you have faced and supports you have sought out (if any). I’d be very grateful for your help! In appreciation of your participation, you will receive a $20 gift card, a summary report of the study, and a letter to your principal noting your contribution to scholarly understanding of new educators’ experiences.

There are no costs associated with participating in this study. Your participation, at any stage, is voluntary. You can skip any question you do not wish to answer or withdraw at any time without consequence. A pseudonym will be used in place of your name during the analysis and reporting of this study to ensure that your identity will remain confidential.

In order to participate, you must be employed as an educator in the United States, have three years or fewer work experience in education, and be over 18 years old. 

If you are interested, please complete the Willingness to Participate form or contact the principal researcher, Bret Staudt Willet (staudtwi@msu.edu). 
Thank you for your consideration!
Bret Staudt Willet 
http://bretsw.com - staudtwi@msu.edu

<hr>

## Appendix B: Willingness to Participate Form {.unnumbered}

*Introduction*

You are being asked to participate in a research study. The purpose of the study is to understand your experiences as a new educator——specifically, any struggles or challenges you have faced and supports you have sought out (if any). You will be asked to participate in an interview lasting 45-60 minutes. 

There are no costs associated with participating in this study. Your participation, at any stage, is voluntary. You can skip any question you do not wish to answer or withdraw at any time without consequence. A pseudonym will be used in place of your name during the analysis and reporting of this study to ensure that your identity will remain confidential.

In order to participate, you must be employed as an educator in the United States, have three years or fewer work experience in education, and be over 18 years old. In appreciation of your participation, you will receive a $20 gift card, a summary report of the study, and a letter to your principal noting your contribution to scholarly understanding of new educators’ experiences.

If you have any questions, please contact the principal researcher, Bret Staudt Willet (staudtwi@msu.edu) or Michigan State University’s Human Research Protection Program (https://hrpp.msu.edu/). 

You indicate that you voluntarily agree to participate in this research study by submitting this form.

*Background Information*

1.	What is your full name?
2.	What is your email address?
3.	How many years of experience do you have as an educator?
4.	What grade level do you primarily work with?
5.	In what content area do you teach? (e.g., math, science, ELA, physical education, etc.)
6.	What type of school do you teach in? 
  a.	(urban, suburban, rural)
7.	What is your school's zip code?
8.	What kind of educator preparation have you had?
  a.	(Undergraduate degree related to education, Graduate degree related to education, Alternative certification, None)
9.	What is your ethnicity?
  a.	(Asian, Black/African, Causasian, Hispanic/Latinx, Middle Eastern, Native American, Pacific Islander, Prefer to self-describe ___, Prefer not to answer)
10.	What is your gender?
  a.	(Female, Male, Non-binary/Third gender, Prefer to self-describe ___, Prefer not to answer)

*Social Media Use*

11.	Which social media platforms do you use? (Choose all that apply.)
  a.	(Facebook, Instagram, LinkedIn, Pinterest, Reddit, Snapchat, TeachersPayTeachers, TikTok, Twitter, YouTube, Other)
12.	How long have you been an active user of social media?
  a.	(Less than 1 year, 1-2 years, 3-5 years, More than 5 years)
13.	How often do you use social media?
  a.	(daily, several time a week, several times a month, rarely)
14.	For what professional purposes do you use social media?
  a.	(Following news and trends in education, Seeking and giving emotional support related to my job, Finding and sharing educational resources, Collaborating with colleagues in education, Other, None)

<hr> 

## Appendix C: Interview Consent (To Be Read Aloud) {.unnumbered}

Thank you for agreeing to do this interview with me today. I am a researcher at Michigan State University, and I am asking you to participate in a research study. The purpose of the study is to understand your experiences as a new educator. I will ask you to answer some questions. This should take about 45-60 minutes. There are no costs associated with participating in this study. Your participation is voluntary. If you do not want to answer any of the questions, please let me know. You can also ask me to stop at any time without consequence. In order to participate, you must be employed as an educator in the United States, have three years or less work experience in education, and be over 18 years old. In appreciation of your participation, you will receive a $20 gift card, a summary report of the study, and a letter to your principal noting your contribution to scholarly understanding of new educators’ experiences. If you have any questions after the interview, please contact me, Bret Staudt Willet (staudtwi@msu.edu), or Michigan State University’s Human Research Protection Program (https://hrpp.msu.edu/). You indicate that you voluntarily agree to participate in this research study by proceeding with the interview. Is it okay if I record our interview?

<p style="color:gray;font-size:11px;">
Note: The Human Research Protection Program (HRPP) and Institutional Review Board (IRB) at Michigan State University classified this study as Exempt 2ii, meaning that “Any disclosure of the human subjects' responses outside the research would not reasonably place the subjects at risk of criminal or civil liability or be damaging to the subjects' financial standing, employability, educational advancement, or reputation.” Because this study is considered “exempt,” I only needed to receive verbal consent at the start of each interview.
</p>

<hr>

## Appendix D: Interview Protocol {.unnumbered}

>Thank you again for agreeing to do this interview with me today. Remember that if there are any questions you don’t want to answer, you are welcome to skip them—just let me know.

**Q1. First, tell me a little bit about yourself.**

-	How many years have you been an educator?
-	What grade level and subjects do you teach?
-	What is your school like? (urban/suburban/rural, zip code)
-	What made you want to become an educator?

**Q2. What are some of the challenges and struggles you have experienced as a new educator? (RQ1)**

*Potential themes and follow up questions:*

-	Everything is new: professional context, feeling professionally isolated
-	Seeing self as professional not student: adult not kid; developing professional identity: understanding self in relation to teaching; values, personal beliefs, convictions, past experiences, present goals;
-	Still learning to teach: planning, developing curriculum, managing classroom practice, improving a specific skill, district-mandated professional development sessions that are too general to be useful
-	Navigating competing values: rethinking beliefs, embracing or reconciling personal values and/or new ideas with those evident in school of employment
-	Agency: purposeful action (why or why not)

**Q3. Have you sought support for these challenges and struggles? (RQ2, RQ3)**

-	What kinds of supports?
-	From whom?
-	Are there any reasons why you have NOT sought supports as a new teacher?
-	Are there any supports you have access to now but are unhelpful or not worth your time?
-	What supports do you need, but are still missing? WHY?

*Potential themes and follow up questions:*

-	Support categories: content expertise (subject-matter questions); time management; classroom management; relating to students; curricular resources; emotional encouragement
-	Types of individuals or groups: former professors; former classmates from preparation program; school administrators; official mentors; subject-matter experts; peers/colleague at school
-	People orientation vs. content orientation; formal vs. informal; local vs. global

**Q4. For each of the supports you mentioned earlier: Do you use social media to access or connect to these supports? (RQ4)**

-	Why or why not?
-	Which social media platforms? How do you use them?

*Potential themes and follow up questions:*

-	Reasons why: ease of use; time efficiency; convenience/just-in-time
  -	People orientation vs. content orientation
-	Reasons why not: distractions; overwhelming number of connections and resources; sense of doing extra work outside school hours
-	Types of individuals or groups: in-person friends; online friends; celebrities; politics; news; other educators; joining a specific group or space; following a particular hashtag
-	Have you found any conflicting messages while looking for help? How did you navigate these? Which advice did you follow? What did you end up doing? How did it go? Why?


**Q5. Let’s return, for a moment, to the challenges and struggles you mentioned earlier—specifically those where you have not sought support or the supports available have been unhelpful. Do you think social media could be useful for accessing or connecting to new or additional supports? (RQ4)**

-	Why or why not?
-	Which social media platforms? How might you use them?

**Q6. For each social media platform mentioned: (RQ4)**

-	How long have you been using ___ [specific social media platform]?
  -	When did you start using for personal reasons? When for professional purposes?
-	Was your initial decision to use related to professional use?
-	How frequently do you use?
-	Has this frequency changed (increased or decreased) after professional use?
-	Overall, has this use for professional purposes been beneficial or detrimental? Why?

*Potential themes and follow up questions:*

-	Huge help, stress relief, stress amplifier, made things complicated, distracting, addictive, etc.


**Q7. What is your school or district’s policy on educators’ use of social media? (RQ4)**

-	In other words, how do administrators feel about you using social media related to work?
-	How have these policies or expectations been communicated to you?

**Q8. Are there any other ways you would link your experiences as a new educator and your use of social media? (RQ4)**

**Q9. Would you like to pick your pseudonym?**

<hr>

## Appendix E: Codebook {.unnumbered}

**Codebook of Emergent Themes and Categories from Qualitative Analysis of Interview Data**

```{r, tidy=TRUE, include=TRUE, echo=FALSE}
codebook <- data.frame(
  Category = c(
    "Change",
    "Scarcity of resources", 
    "Conflicting teaching beliefs", 
    "Planning", 
    "Enacting practice", 
    "Connecting socially", 
    "In-school", 
    "Out-of-school", 
    "Browse", 
    "Ask",
    "Exchange"
  ),
  Definition = c(
    "Change in circumstances, disruptions, or uncertainty experienced by new teachers (e.g., administrative turnover, starting to teach a new course mid-year).",
    "Absence or shortage of resources for new teachers (e.g., a new teachers’ limited budget, absence of curriculum, missing classroom materials, poor physical conditions of school). Contains an explicit comment to the effect of “I don’t have the resources I need.”", 
    "Tension experienced by new teachers between their previously held beliefs about teaching and learning and those encountered in their school of employment (e.g., interpretation of state standards, philosophy of student discipline, how to teach curriculum).", 
    "New teachers’ need to prepare for teaching ahead of time (e.g., generating ideas, creating curriculum, writing lesson plans, finding appropriate resources).", 
    "New teachers’ need to learn more about and improve their teaching and working directly with students in the classroom (e.g., classroom management, student engagement, helping students).", 
    "New teachers’ need to be socially connected, regardless of modality. Functions positively as a type of social glue (e.g., chatting with friends, venting about work) and negatively as social comparison (e.g., feeling inadequate when looking at a peer or colleague’s work).", 
    "Potential source of assistance for new teachers that is located within the school building, whether formally required (e.g., mentor teacher, professional learning community), informally initiated by the new teacher (e.g., talking to colleagues in the teachers’ lounge), or accessed by any modality (e.g., offline, social media)", 
    "Potential source of assistance for new teachers that is located outside the school building, whether formally required (e.g., district-wide professional development gathering) or informally initiated by the new teacher (e.g., family, friends, resources retrieved online, social media links to anyone beyond in-school colleagues).", 
    "New teachers seeking supports for self-interested reasons by looking through existing materials (e.g., looking up resources on TeachersPayTeachers.com, observing posts in a Facebook group, watching YouTube videos). Includes determining whether and how to use available resources and supports.", 
    "New teachers seeking supports for self-interested reasons by inquiring about the existence of materials (e.g., making needs known, venting or personal sharing in hopes of receiving emotional encouragement). Includes determining whether and how to use available resources and supports.",
    "New teachers seeking supports by participating as a member of a learning community or team, which may be formal or informal, harmonious or conflictual. Characterized by interaction and dialogue—that is, mutual exchange to satisfy mutual interests (e.g., contributing ideas to a group, giving advice on social media, conversing to determine best practices)."
  )
)

knitr::kable(codebook,
             booktabs = TRUE) %>%
  kableExtra::kable_styling(full_width=TRUE, font_size = 12) %>%
  kableExtra::column_spec(1, bold=TRUE, border_right=FALSE) %>%
  pack_rows("RQ1. Reasons", 
            1, 3, 
            label_row_css = "background-color: #23373B; color: #fff;") %>%
  pack_rows("RQ2. Supports", 
            4, 6, 
            label_row_css = "background-color: #23373B; color: #fff;") %>%
  pack_rows("RQ3. Connections", 
            7, 8, 
            label_row_css = "background-color: #23373B; color: #fff;") %>%
  pack_rows("RQ4. Engagement", 
            9, 11, 
            label_row_css = "background-color: #23373B; color: #fff;")
```
