# References

Alemdag, E., & Erdem, M. (2017). Designing an e-mentoring program for novice teachers in Turkey and investigating online interactions and program outcomes. *Mentoring & Tutoring: Partnership in Learning, 25*(2), 123-150. https://doi.org/10.1080/13611267.2017.1327394

Anderson, L. M., & Stillman, J. A. (2013). Student teaching's contribution to preservice teacher development: A review of research focused on the preparation of teachers for urban and high-needs contexts. *Review of Educational Research, 83*(1), 3–69. https://doi.org/10.3102/0034654312468619

ATLAS.ti. (2019). ATLAS.ti 8 Mac (Version 8.4.0) [Computer software]. Berlin, Germany: ATLAS.ti Scientific Software Development GmbH. Available from https://atlasti.com/product/mac-os-edition/

Barron, B. (2006). Interest and self-sustained learning as catalysts of development: A learning ecology perspective. *Human development, 49*(4), 193-224. https://doi.org/10.1159/000094368

Borko, H. & Putnam, R. T. (1996). Learning to teach. In D. C. Berliner & R. C. Calfee (Eds.), *Handbook of educational psychology* (pp. 673-708). New York, NY: MacMillan.

Carpenter, J. P., & Krutka, D. G. (2014). How and why educators use Twitter: A survey of the field. *Journal of Research on Technology in Education, 46*, 414–434. https://doi.org/10.1080/15391523.2014.925701

Carpenter, J., McDade, C., & Childers, S. (2018, March). Advice seeking and giving in the Reddit r/Teachers online space. In E. Langran & J. Borup (Eds.), *Proceedings of Society for Information Technology & Teacher Education (SITE) International Conference 2018* (pp. 2207-2215). Association for the Advancement of Computing in Education (AACE). Retrieved from https://www.learntechlib.org/p/182831/

Carver-Thomas, D., & Darling-Hammond, L. (2017). *Teacher turnover: Why it matters and what we can do about it*. Palo Alto, CA: Learning Policy Institute.

Chen, G. M. (2011). Tweet this: A uses and gratifications perspective on how active Twitter use gratifies a need to connect with others. *Computers in Human Behavior, 27*, 755–762. https://doi.org/10.1016/j.chb.2010.10.023

Clandinin, D. J., Long, J., Schaefer, L., Downey, C. A., Steeves, P., Pinnegar, E., Robblee, S. M., & Wnuk, S. (2015). Early career teacher attrition: Intentions of teachers beginning. *Teaching Education, 26*(1), 1-16. https://doi.org/10.1080/10476210.2014.996746

Collins, K. M. T., Onwuegbuzie, A. J., & Sutton, I. L. (2006). A model incorporating the rationale and purpose for conducting mixed methods research in special education and beyond. *Learning Disabilities: A Contemporary Journal, 4*, 67-100.

Creswell, J. W. (2011). Controversies in mixed methods research. In N. K. Denzin, & Y. S. Lincoln (Eds.), *The SAGE handbook of qualitative research* (4th ed., pp. 269-283). Thousand Oaks, CA: SAGE.

Creswell, J. W. (2014). *Research design: Qualitative, quantitative, and mixed methods approaches* (4th ed.). Thousand Oaks, CA: SAGE.

Creswell, J. W., & Miller, D. L. (2000). Determining validity in qualitative inquiry. *Theory Into Practice, 39*(3), 124-130. https://doi.org/10.1207/s15430421tip3903_2

Cuddapah, J. L., & Clayton, C. D. (2011). Using Wenger’s communities of practice to explore a new teacher cohort. *Journal of Teacher Education, 62*(1), 62-75. https://doi.org/10.1177/0022487110377507

Davis, K. (2015). Teachers’ perceptions of Twitter for professional development. Disability and Rehabilitation, 37, 1551-1558. https://doi.org/10.3109/09638288.2015.1052576
Davis, B., & Higdon, K. (2008). The effects of mentoring/induction support on beginning teachers. *Journal of Research in Childhood Education, 22*, 261-274. https://doi.org/10.1080/02568540809594626

DeVellis, R. F. (2017). *Scale development: Theory and applications* (4th ed.). Thousand Oaks, CA: SAGE.

Duncan-Howell, J. (2010). Teachers making connections: Online communities as a source of professional learning. *British Journal of Educational Technology, 41*, 324-340. https://doi.org/10.1111/j.1467-8535.2009.00953.x

Dunn, A. H. (2018). Leaving a profession after it's left you: Teachers' public resignation letters as resistance amidst neoliberalism. *Teachers College Record, 120*(9), 1-34. Retrieved from https://www.tcrecord.org/content.asp?contentid=22107

Edelmann, N. (2013). Reviewing the definitions of "lurkers" and some implications for online research. *Cyberpsychology, Behavior, and Social Networking, 16*, 645-649. https://doi.org/10.1089/cyber.2012.0362

Evertson, C. M., & Smithey, M. W. (2000). Mentoring effects on protégés’ classroom practice: An experimental field study. *Journal of Educational Research, 93*(5), 294-304. https://doi.org/10.1080/00220670009598721

Fantilli, R. D., & McDougall, D. E. (2009). A study of novice teachers: Challenges and supports in the first years. *Teaching and Teacher Education, 25*, 814-825. https://doi.org/10.1016/j.tate.2009.02.021

Feiman-Nemser, S., & Buchmann, M. (1985). Pitfalls of experience in teacher preparation. *Teachers College Record, 87*, 53–65.

Flanigan, R. (2011, October 24). Professional learning networks taking off. *Education Week*. Retrieved from https://www.edweek.org/ew/articles/2011/10/26/09edtech-network.h31.html

Fox, A., & Bird, T. (2017). The challenge to professionals of using social media: Teachers in England negotiating personal-professional identities. *Education and Information Technologies, 22*(2), 647-675. https://doi.org/10.1007/s10639-015-9442-0

Fresko, B., & Alhija, F. N.-A. (2015). Induction seminars as professional learning communities for beginning teachers. *Asia-Pacific Journal of Teacher Education, 43*(1), 36-48, https://doi.org/10.1080/1359866X.2014.928267

Glaser, B. G., & Strauss, A. L. (1967). The discovery of grounded theory: Strategies for qualitative research. *Observations* (Vol. 1). New Brunswick, NJ: AldineTransaction. https://doi.org/10.2307/2575405

Glesne, C. (2016). *Becoming qualitative researchers: An introduction* (5th ed.). Boston, MA: Pearson.

Greenhalgh, S. P., & Koehler, M. J. (2017). 28 days later: Twitter hashtags as “just in time” teacher professional development. *TechTrends, 61*, 273-281. https://doi.org/10.1007/s11528-016-0142-4

Greenhow, C. M., Gleason, B., & Staudt Willet, K. B. (2019). Social scholarship revisited: Changing scholarly practices in the age of social media. *British Journal of Educational Technology, 50*, 987-1004. https://doi.org/10.1111/bjet.12772/

Greenhow, C., & Lewin, C. (2016). Social media and education: Reconceptualizing the boundaries of formal and informal learning. *Learning, Media and Technology, 41*(1), 6-30. https://doi.org/10.1080/17439884.2015.1064954

Greenhow, C., Robelia, B., & Hughes, J. E. (2009). Learning, teaching, and scholarship in a digital age: Web 2.0 and classroom research: What path should we take now?. *Educational Researcher, 38*(4), 246-259. https://doi.org/10.3102/0013189X09336671

Hackman, M., & Morath, E. (2018, December 28). Teachers quit jobs at highest rate on record: Small raises, budget frustration and opportunities elsewhere persuade teachers and other public-education workers to move on. *Wall Street Journal*. Retrieved from https://www.wsj.com/articles/teachers-quit-jobs-at-highest-rate-on-record-11545993052 

Horn, I. S., Nolen, S. B., Ward, C., & Campbell, S. S. (2008). Developing practices in multiple worlds: The role of identity in learning to teach. *Teacher Education Quarterly, 35*(3), 61-72. Retrieved from https://eric.ed.gov/?id=EJ831716

Hu, S., Torphy, K. T., Opperman, A., Jansen, K., & Lo, Y. J. (2018). What do teachers share within socialized knowledge communities: A case of Pinterest. *Journal of Professional Capital and Community, 3*(2), 97-122. https://doi.org/10.1108/JPCC-11-2017-0025

Humphreys, A. (2016). *Social media: Enduring principles*. New York, NY: Oxford University Press.

Hur, J. W., & Brush, T. A. (2009). Teacher participation in online communities: Why do teachers want to participate in self-generated online communities of K–12 teachers?. *Journal of Research on Technology in Education, 41*, 279-303. https://doi.org/10.1080/15391523.2009.10782532

Ingersoll, R. M. (2012). Beginning teacher induction: What the data tell us. *Phi Delta Kappan, 93*(8), 47-51. https://doi.org/10.1177/003172171209300811

Ingersoll, R. M., & Strong, M. (2011). The impact of induction and mentoring programs for beginning teachers: A Critical Review of the Research. *Review of Education Research, 81*, 201–233. https://doi.org/10.3102/0034654311403323

International Society for Technology in Education. (n.d.). Professional learning networks [Web page]. Retrieved from https://www.iste.org/learn/about-iste-plns

Jenkins, H. (2009). *Confronting the challenges of participatory culture: Media education for the 21st century*. Cambridge, MA: MIT Press.

Jones, A., & Preece, J. (2006). Online communities for teachers and lifelong learners: A framework for comparing similarities and identifying differences in communities of practice and communities of interest. *International Journal of Learning Technology, 2*(2), 112–137. https://doi.org/10.1504/IJLT.2006.010615

Kang, S., & Berliner, D. C. (2012). Characteristics of teacher induction programs and turnover rates of beginning teachers. *The Teacher Educator, 47*(4), 268-282. https://doi.org/10.1080/08878730.2012.707758

Kelly, N., & Antonio, A. (2016). Teacher peer support in social network sites. *Teaching and Teacher Education, 56*, 138-149. https://doi.org/10.1016/j.tate.2016.02.007

Kim, C. M., Frank, K. A., & Spillane, J. P. (2018). Relationships among teachers' formal and informal positions and their incoming student composition. *Teachers College Record, 120*(3), 1-34. Retrieved from https://www.tcrecord.org/content.asp?contentid=22072

Krutka, D. G., Carpenter, J. P., & Trust, T. (2016). Elements of engagement: A model of teacher interactions via professional learning networks. *Journal of Digital Learning in Teacher Education, 32*(4), 150-158. https://doi.org/10.1080/21532974.2016.1206492

Krutka, D. G., Carpenter, J. P., & Trust, T. (2017). Enriching professional learning networks: A framework for identification, reflection, and intention. *TechTrends, 61*, 246-252. https://doi.org/10.1007/s11528-016-0141-5

Landis, J. R., & Koch, G. G. (1977). The measurement of observer agreement for categorical data. *Biometrics, 33*(1), 159–174. https://doi.org/10.2307/2529310

Lantz-Andersson, A., Lundin, M., & Selwyn, N. (2018). Twenty years of online teacher communities: A systematic review of formally-organized and informally-developed professional learning groups. *Teaching and Teacher Education, 75*, 302–315. https://doi.org/10.1016/j.tate.2018.07.008

Lave, J., & Wenger, E. (1991). *Situated learning: Legitimate peripheral participation*. New York, NY: Cambridge University Press.

Lincoln, Y. S., & Guba, E. G. (1985). *Naturalistic inquiry*. Newbury Park, CA: SAGE.

Luo, T., & Clifton, L. (2017). Examining collaborative knowledge construction in microblogging-based learning environments. *Journal of Information Technology Education: Research, 16*, 365-390. https://doi.org/10.28945/3869

Macià, M., & García, I. (2016). Informal online communities and networks as a source of teacher professional development: A review. *Teaching and Teacher Education, 55*, 291-307. https://doi.org/10.1016/j.tate.2016.01.021

März, V. &, Kelchtermans, G. (2020). The networking teacher in action: A qualitative analysis of early career teachers' induction process. *Teaching and Teacher Education, 87*, 1-14. https://doi.org/10.1016/j.tate.2019.102933

Maxwell, J. A. (2013). *Qualitative research design: An interactive approach* (3rd ed.). Thousand Oaks, CA: SAGE.

Mercieca, B., & Kelly, N. (2018). Early career teacher peer support through private groups in social media. *Asia-Pacific Journal of Teacher Education, 46*(1), 61-77. https://doi.org/10.1080/1359866X.2017.1312282

Nielson, J. (2006). The 90-9-1 rule for participation inequality in social media and online communities. Nielson Norman Group. Retrieved from https://www.nngroup.com/articles/participation-inequality/

Owen, N., Fox, A., & Bird, T. (2016). The development of a small-scale survey instrument of UK teachers to study professional use (and non-use) of and attitudes to social media. *International Journal of Research & Method in Education, 39*(2), 170-193. https://doi.org/10.1080/1743727X.2015.1041491

Packard, B. W. (2003). Student training promotes mentoring awareness and action. *The Career Development Quarterly, 51*(4), 335-345. https://doi.org/10.1002/j.2161-0045.2003.tb00614.x

Patton, M. Q. (2002). *Qualitative evaluation and research methods* (3rd ed.). Thousand Oaks, CA: SAGE.

Pearce, J., & Morrison, C. (2011). Teacher identity and early career resilience: Exploring the links. *Australian Journal of Teacher Education, 36*, 47–59. https://doi.org/10.14221/ajte.2011v36n1.4

Prestridge, S. (2017). Conceptualising self-generating online teacher professional development. *Technology, Pedagogy and Education, 26*(1), 85-104. https://doi.org/10.1080/1475939X.2016.1167113

Prestridge, S. (2019). Categorising teachers’ use of social media for their professional learning: A self-generating professional learning paradigm. *Computers & Education, 129*, 143-158. https://doi.org/10.1016/j.compedu.2018.11.003

Putnam, R. T., & Borko, H. (2000). What do new views of knowledge and thinking have to say about research on teacher learning?. *Educational Researcher, 29*, 4-15. https://doi.org/10.3102/0013189X029001004

Qualtrics. (n.d.). Online survey software [Computer software]. Seattle, WA: Qualtrics International Inc. Available from https://www.qualtrics.com/research-core/survey-software/

R Core Team. (2018). R: A language and environment for statistical computing (Version 3.5.2) [Computer software]. Vienna, Austria: R Foundation for Statistical Computing. Available from https://www.R-project.org/

Rehm, M., & Notten, A. (2016). Twitter as an informal learning space for teachers!? The role of social capital in Twitter conversations among teachers. *Teaching and Teacher Education, 60*, 215–223. https://doi.org/10.1016/j.tate.2016.08.015

Reich, J., Levinson, M., & Johnston, W. (2011). Using online social networks to foster preservice teachers’ membership in a networked community of praxis. *Contemporary Issues in Technology and Teacher Education, 11*(4), 382-397. Retrieved from https://www.citejournal.org/volume-11/issue-4-11/social-studies/using-online-social-networks-to-foster-preservice-teachers-membership-in-a-networked-community-of-praxis/

Remler, D. K., & Van Ryzin, G. G. (2011). *Research methods in practice: Strategies for description and causation*. Thousand Oaks, CA: SAGE.

Ronfeldt, M., Loeb, S., & Wyckoff, J. (2013). How teacher turnover harms student achievement. *American Educational Research Journal, 50*(1), 4-36. https://doi.org/10.3102/0002831212463813

Ronfeldt, M., & McQueen, K. (2017). Does new teacher induction really improve retention? *Journal of Teacher Education, 68*(4), 394-410. https://doi.org/10.1177/0022487117702583

Saldaña, J. (2016). *The coding manual for qualitative researchers* (3rd ed.). London, UK: SAGE.

Selwyn, N., Nemorin, S., & Johnson, N. (2017). High-tech, hard work: An investigation of teachers’ work in the digital age. *Learning, Media and Technology, 42*, 390-405. https://doi.org/10.1080/17439884.2016.1252770

Singletary, T. J., & Anderson, H. (1995) Computer mediated teacher induction. In Z. L. Berge & M. P. Collins (Eds.), *Computer-mediated communication and the online classroom* (Vol. 1: Overview and perspectives). Cresskill, NJ: Hampton Press.

Smith Risser, H. (2013). Virtual induction: A novice teacher’s use of Twitter to form an informal mentoring network. *Teaching and Teacher Education, 35*, 25–33. https://doi.org/10.1016/j.tate.2013.05.001

Stanulis, R. N., & Floden, R. E. (2009). Intensive mentoring as a way to help beginning teachers develop balanced instruction. *Journal of Teacher Education, 60*(2), 112-122. https://doi.org/10.1177/0022487108330553

Stanulis, R. N., Little, S., & Wibbens, E. (2012). Intensive mentoring that contributes to change in beginning elementary teachers’ learning to lead classroom discussions. *Teaching and Teacher Education, 28*, 32-43. https://doi.org/10.1016/j.tate.2011.08.007

Staudt Willet, K. B. (2019). Revisiting how and why educators use Twitter: Tweet types and purposes in #Edchat. *Journal of Research on Technology in Education, 51*, 273-289. https://doi.org/10.1080/15391523.2019.1611507

Staudt Willet, K. B., & Carpenter, J. P. (2019, March). Educators on the front page of the Internet: Education-related subreddits as learning spaces. In K. Graziano (Ed.), *Proceedings of Society for Information Technology & Teacher Education (SITE) International Conference 2019* (pp. 2787-2795). Las Vegas, NV: Association for the Advancement of Computing in Education (AACE). Retrieved from https://www.learntechlib.org/p/208040/

Staudt Willet, K. B., Koehler, M. J., & Greenhalgh, S. P. (2017, March). A tweet by any other frame: Three approaches to studying educator interactions on Twitter. In P. Resta & S. Smith (Eds.), *Proceedings of Society for Information Technology & Teacher Education (SITE) International Conference 2017* (pp. 1823-1830). Austin, TX: Association for the Advancement of Computing in Education (AACE). Retrieved from https://www.learntechlib.org/p/177469/

Strahan, R., & Gerbasi, K. C. (1972). Short, homogeneous versions of the Marlow-Crowne social desirability scale. *Journal of Clinical Psychology, 28*(2), 191-193. https://doi.org/10.1002/1097-4679(197204)28:2<191::AID-JCLP2270280220>3.0.CO;2-G

Strano, M. M., & Queen, J. W. (2012). Covering your face on Facebook. *Journal of Media Psychology: Theories, Methods, andApplications, 24*, 166–180. https://doi.org/10.1027/1864-1105/a000076

Thomas, L., Tuytens, M., Devos, G., Kelchtermans, G., & Vanderlinde, R. (2019). Beginning teachers’ professional support: A mixed methods social network study. *Teaching and Teacher Education, 83*, 134-147. https://doi.org/10.1016/j.tate.2019.04.008

Thompson, J., Windschitl, M., & Braaten, M. (2013). Developing a theory of ambitious early-career teacher practice. *American Educational Research Journal, 50*, 574–615. https://doi.org/10.3102/0002831213476334

Tour, E. (2017). Teachers’ self-initiated professional learning through personal learning networks. *Technology, Pedagogy and Education, 26*(2), 179-192. https://doi.org/10.1080/1475939X.2016.1196236

Trust, T. (2012). Professional learning networks designed for teacher learning. *Journal of Digital Learning in Teacher Education, 28*(4), 133-138. https://doi.org/10.1080/21532974.2012.10784693

Trust, T., & Horrocks, B. (2017). “I never feel alone in my classroom”: Teacher professional growth within a blended community of practice. *Professional Development in Education, 43*(4), 645–665. https://doi.org/10.1080/19415257.2016.1233507

Trust, T., Krutka, D. G., & Carpenter, J. P. (2016). “Together we are better”: Professional learning networks for teachers. *Computers & Education, 102*, 15-34. https://doi.org/10.1016/j.compedu.2016.06.007

Valdez, A. C., Schaar, A. K., & Ziefle, M. (2012). State of the (net)-work address developing criteria for applying social networking to the work environment. *Work, 41*, 3459–3467. https://doi.org/10.3233/WOR- 2012-0625-3459

Wesely, P. M. (2013). Investigating the community of practice of world language educators on Twitter. *Journal of Teacher Education, 64*, 305–318. https://doi.org/10.1177/0022487113489032

Wray, K. A., & Richmond, G. (2018). Factors shaping the agency of beginning science teachers working in high-poverty schools. *Journal of Science Teacher Education, 29*(8), 785-803. https://doi.org/10.1080/1046560X.2018.1514824

Xie, Y. (2019a). bookdown: Authoring books and technical documents with R markdown (Version 0.16) [R package]. Available from https://CRAN.R-project.org/package=bookdown/

Xie, Y. (2019b). knitr: A general-purpose package for dynamic report
generation in R (Version 1.26.1) [R package]. Available from https://CRAN.R-project.org/package=knitr/

Xing, W., & Gao, F. (2018). Exploring the relationship between online discourse and commitment in Twitter professional learning communities. *Computers & Education, 126*, 388-398. https://doi.org/10.1016/j.compedu.2018.08.010

Yadav, A., Gretter, S., Hambrusch, S., & Sands, P. (2016). Expanding computer science education in schools: Understanding teacher experiences and challenges. *Computer Science Education, 26*(4), 235-254. https://doi.org/10.1080/08993408.2016.1257418

Zhukova, O. (2018). Novice teachers’ concerns, early professional experiences and development: Implications for theory and practice. *Discourse and Communication for Sustainable Education, 9*(1), 100-114. https://doi.org/10.2478/dcse-2018-0008

Zoom. (n.d.). Zoom meetings [Computer software]. San Jose, CA: Zoom Video Communications, Inc. Available from https://zoom.us/
