# References {.unnumbered}

Anderson, L. M., & Stillman, J. A. (2013). Student teaching's contribution to preservice teacher development: A review of research focused on the preparation of teachers for urban and high-needs contexts. Review of *Educational Research, 83*(1), 3–69. https://doi.org/10.3102/0034654312468619

Bandura, A. (2001). Social cognitive theory: An agentic perspective. *Annual Review of Psychology, 52*(1), 1-26. https://doi.org/10.1146/annurev.psych.52.1.1

Barron, B. (2006). Interest and self-sustained learning as catalysts of development: A learning ecology perspective. *Human Development, 49*(4), 193-224. https://doi.org/10.1159/000094368

Bartell, T., Cho, C., Drake, C., Petchauer, E., & Richmond, G. (2019). Teacher agency and resilience in the age of neoliberalism. *Journal of Teacher Education, 70*(4), 302-305. https://doi.org/10.1177/0022487119865216

Beach, P. (2017). Self-directed online learning: A theoretical model for understanding elementary teachers’ online learning experiences. *Teaching and Teacher Education, 61*, 60–72. https://doi.org/10.1016/j.tate.2016.10.007

Bolger, N., & Laurenceau, J.-P. (2013). *Intensive longitudinal methods: An introduction to diary and experience sampling research*. Guilford Press.

boyd, d. (2007). Why youth <3 social network sites: The role of networked publics in teenage social life. In D. Buckingham (Ed.), *Youth, identity, and digital media* (pp. 119-142). MIT Press.

Bozkurt, A., Koutropoulos, A., Singh, L., & Honeychurch, S. (2020). On lurking: Multiple perspectives on lurking within an educational community. *The Internet and Higher Education, 44*, 100709. https://doi.org/10.1016/j.iheduc.2019.100709

Burkell, J., Fortier, A., Wong, L. L. Y. C., & Simpson, J. L. (2014). Facebook: Public space, or private space?. *Information, Communication & Society, 17*(8), 974-985. https://doi.org/10.1080/1369118X.2013.870591

Carpenter, J. P., & Harvey, S. (2019). “There's no referee on social media”: Challenges in educator professional social media use. *Teaching and Teacher Education, 86*, 102904. https://doi.org/10.1016/j.tate.2019.102904

Carpenter, J. P., & Krutka, D. G. (2014). How and why educators use Twitter: A survey of the field. *Journal of Research on Technology in Education, 46*, 414–434. https://doi.org/10.1080/15391523.2014.925701

Carpenter, J. P., Krutka, D. G., & Trust, T. (2021). Continuity and change in educators’ professional learning networks. *Journal of Educational Change*. https://doi.org/10.1007/s10833-020-09411-1

Carpenter, J. P., Morrison, S. A., Craft, M., & Lee, M. (2020). How and why are educators using Instagram?. *Teaching and Teacher Education, 96*, 103149. https://doi.org/10.1016/j.tate.2020.103149

Carver-Thomas, D., & Darling-Hammond, L. (2017). *Teacher turnover: Why it matters and what we can do about it*. Learning Policy Institute. https://learningpolicyinstitute.org/product/teacher-turnover-report

Clandinin, D. J., Long, J., Schaefer, L., Downey, C. A., Steeves, P., Pinnegar, E., Robblee, S. M., & Wnuk, S. (2015). Early career teacher attrition: Intentions of teachers beginning. *Teaching Education, 26*(1), 1-16. https://doi.org/10.1080/10476210.2014.996746

Creswell, J. W., & Miller, D. L. (2000). Determining validity in qualitative inquiry. *Theory Into Practice, 39*(3), 124-130. https://doi.org/10.1207/s15430421tip3903_2

Cuddapah, J. L., & Clayton, C. D. (2011). Using Wenger’s communities of practice to explore a new teacher cohort. *Journal of Teacher Education, 62*(1), 62-75. https://doi.org/10.1177/0022487110377507

Davis, K. (2015). Teachers’ perceptions of Twitter for professional development. *Disability and Rehabilitation, 37*, 1551-1558. https://doi.org/10.3109/09638288.2015.1052576

Davis, B., & Higdon, K. (2008). The effects of mentoring/induction support on beginning teachers. *Journal of Research in Childhood Education, 22*, 261-274. https://doi.org/10.1080/02568540809594626

Duncan-Howell, J. (2010). Teachers making connections: Online communities as a source of professional learning. *British Journal of Educational Technology, 41*, 324-340. https://doi.org/10.1111/j.1467-8535.2009.00953.x

Dunn, A. H. (2018). Leaving a profession after it's left you: Teachers' public resignation letters as resistance amidst neoliberalism. *Teachers College Record, 120*(9), 1-34. https://www.tcrecord.org/content.asp?contentid=22107

Edelmann, N. (2013). Reviewing the definitions of "lurkers" and some implications for online research. *Cyberpsychology, Behavior, and Social Networking, 16*, 645-649. https://doi.org/10.1089/cyber.2012.0362

Fantilli, R. D., & McDougall, D. E. (2009). A study of novice teachers: Challenges and supports in the first years. *Teaching and Teacher Education, 25*(6), 814-825. https://doi.org/10.1016/j.tate.2009.02.021

Feiman-Nemser, S., & Buchmann, M. (1985). Pitfalls of experience in teacher preparation. *Teachers College Record, 87*, 53–65. https://www.tcrecord.org/content.asp?contentid=677

Fox, A., & Bird, T. (2017). The challenge to professionals of using social media: Teachers in England negotiating personal-professional identities. *Education and Information Technologies, 22*(2), 647-675. https://doi.org/10.1007/s10639-015-9442-0

Fresko, B., & Alhija, F. N.-A. (2015). Induction seminars as professional learning communities for beginning teachers. *Asia-Pacific Journal of Teacher Education, 43*(1), 36-48, https://doi.org/10.1080/1359866X.2014.928267

Glaser, B. G., & Strauss, A. L. (1967). The discovery of grounded theory: Strategies for qualitative research. *Observations* (Vol. 1). AldineTransaction. https://doi.org/10.2307/2575405

Glesne, C. (2016). *Becoming qualitative researchers: An introduction* (5th ed.). Pearson.

Greenhalgh, S. P., & Koehler, M. J. (2017). 28 days later: Twitter hashtags as “just in time” teacher professional development. *TechTrends, 61*, 273-281. https://doi.org/10.1007/s11528-016-0142-4

Greenhalgh, S. P., Rosenberg, J. M., Staudt Willet, K. B., Koehler, M. J., & Akcaoglu, M. (2020). Identifying multiple learning spaces within a single teacher-focused Twitter hashtag. *Computers and Education, 148*, 103809. https://doi.org/10.1016/j.compedu.2020.103809

Greenhow, C. M., Gleason, B., & Staudt Willet, K. B. (2019). Social scholarship revisited: Changing scholarly practices in the age of social media. B*ritish Journal of Educational Technology, 50*, 987-1004. https://doi.org/10.1111/bjet.12772/

Greenhow, C., & Lewin, C. (2016). Social media and education: Reconceptualizing the boundaries of formal and informal learning. *Learning, Media and Technology, 41*(1), 6-30. https://doi.org/10.1080/17439884.2015.1064954

Greenhow, C., Robelia, B., & Hughes, J. E. (2009). Learning, teaching, and scholarship in a digital age: Web 2.0 and classroom research: What path should we take now?. *Educational Researcher, 38*(4), 246-259. https://doi.org/10.3102/0013189X09336671

Hackman, M., & Morath, E. (2018, December 28). Teachers quit jobs at highest rate on record: Small raises, budget frustration and opportunities elsewhere persuade teachers and other public-education workers to move on. *Wall Street Journal*. https://www.wsj.com/articles/teachers-quit-jobs-at-highest-rate-on-record-11545993052 

Horn, I. S., Nolen, S. B., Ward, C., & Campbell, S. S. (2008). Developing practices in multiple worlds: The role of identity in learning to teach. *Teacher Education Quarterly, 35*(3), 61-72. https://eric.ed.gov/?id=EJ831716

Hu, S., Torphy, K. T., Opperman, A., Jansen, K., & Lo, Y. J. (2018). What do teachers share within socialized knowledge communities: A case of Pinterest. *Journal of Professional Capital and Community, 3*(2), 97-122. https://doi.org/10.1108/JPCC-11-2017-0025

Hur, J. W., & Brush, T. A. (2009). Teacher participation in online communities: Why do teachers want to participate in self-generated online communities of K–12 teachers?. *Journal of Research on Technology in Education, 41*, 279-303. https://doi.org/10.1080/15391523.2009.10782532

Ingersoll, R. M. (2012). Beginning teacher induction: What the data tell us. *Phi Delta Kappan, 93*(8), 47-51. https://doi.org/10.1177/003172171209300811

Ingersoll, R. M., & Strong, M. (2011). The impact of induction and mentoring programs for beginning teachers: A Critical Review of the Research. *Review of Education Research, 81*, 201–233. https://doi.org/10.3102/0034654311403323

Jones, A., & Preece, J. (2006). Online communities for teachers and lifelong learners: A framework for comparing similarities and identifying differences in communities of practice and communities of interest. *International Journal of Learning Technology, 2*(2), 112–137. https://doi.org/10.1504/IJLT.2006.010615

Kang, S., & Berliner, D. C. (2012). Characteristics of teacher induction programs and turnover rates of beginning teachers. *The Teacher Educator, 47*(4), 268-282. https://doi.org/10.1080/08878730.2012.707758

Kelly, N., & Antonio, A. (2016). Teacher peer support in social network sites. *Teaching and Teacher Education, 56*, 138-149. https://doi.org/10.1016/j.tate.2016.02.007

Kim, C. M., Frank, K. A., & Spillane, J. P. (2018). Relationships among teachers' formal and informal positions and their incoming student composition. *Teachers College Record, 120*(3), 1-34. https://www.tcrecord.org/content.asp?contentid=22072

Koehler, M. J., Shelton, C. C., Carpenter, J. P., & Greenhalgh, S. P. (2020). Where does all the money go? Free and paid transactions on TeachersPayTeachers.com. *Teachers College Record*. https://www.tcrecord.org/Content.asp?ContentID=23478

Krutka, D. G., Carpenter, J. P., & Trust, T. (2017). Enriching professional learning networks: A framework for identification, reflection, and intention. *TechTrends, 61*, 246-252. https://doi.org/10.1007/s11528-016-0141-5

Landis, J. R., & Koch, G. G. (1977). The measurement of observer agreement for categorical data. *Biometrics, 33*(1), 159–174. https://doi.org/10.2307/2529310

Lantz-Andersson, A., Lundin, M., & Selwyn, N. (2018). Twenty years of online teacher communities: A systematic review of formally-organized and informally-developed professional learning groups. *Teaching and Teacher Education, 75*, 302–315. https://doi.org/10.1016/j.tate.2018.07.008

Lave, J., & Wenger, E. (1991). *Situated learning: Legitimate peripheral participation*. Cambridge University Press.

Lincoln, Y. S., & Guba, E. G. (1985). *Naturalistic inquiry*. SAGE.

Macià, M., & García, I. (2016). Informal online communities and networks as a source of teacher professional development: A review. *Teaching and Teacher Education, 55*, 291-307. https://doi.org/10.1016/j.tate.2016.01.021

Marwick, A. E., & boyd, d. (2011). I tweet honestly, I tweet passionately: Twitter users, context collapse, and the imagined audience. *New Media & Society, 13*(1), 114-133. https://doi.org/10.1177/1461444810365313

März, V., &, Kelchtermans, G. (2020). The networking teacher in action: A qualitative analysis of early career teachers' induction process. *Teaching and Teacher Education, 87*, 1-14. https://doi.org/10.1016/j.tate.2019.102933

National Center for Education Statistics. (2020, May). Characteristics of public school teachers. *The condition of education* [report]. https://nces.ed.gov/programs/coe/indicator_clr.asp

Nielson, J. (2006). *The 90-9-1 rule for participation inequality in social media and online communities*. Nielson Norman Group. https://www.nngroup.com/articles/participation-inequality/

Participate Inc. (2019, February 25). Update regarding Twitter chats on Participate! [Web archive]. https://explore.participate.com/twitter-chats

Pearce, J., & Morrison, C. (2011). Teacher identity and early career resilience: Exploring the links. *Australian Journal of Teacher Education, 36*, 47–59. https://doi.org/10.14221/ajte.2011v36n1.4

Peters, M., & Romero, M. (2019). Lifelong learning ecologies in online higher education: Students' engagement in the continuum between formal and informal learning. *British Journal of Educational Technology, 50*(4), 1729-1743. https://doi.org/10.1111/bjet.12803

Prestridge, S. (2017). Conceptualising self-generating online teacher professional development. *Technology, Pedagogy and Education, 26*(1), 85-104. https://doi.org/10.1080/1475939X.2016.1167113

Prestridge, S. (2019). Categorising teachers’ use of social media for their professional learning: A self-generating professional learning paradigm. *Computers & Education, 129*, 143-158. https://doi.org/10.1016/j.compedu.2018.11.003

Putnam, R. T., & Borko, H. (2000). What do new views of knowledge and thinking have to say about research on teacher learning?. *Educational Researcher, 29*, 4-15. https://doi.org/10.3102/0013189X029001004

Ranieri, M., Manca, S., & Fini, A. (2012). Why (and how) do teachers engage in social networks? An exploratory study of professional use of Facebook and its implications for lifelong learning. *British Journal of Educational Technology, 43*, 754–769. https://doi.org/10.1111/j.1467-8535.2012.01356.x

Rehm, M., & Notten, A. (2016). Twitter as an informal learning space for teachers!? The role of social capital in Twitter conversations among teachers. *Teaching and Teacher Education, 60*, 215–223. https://doi.org/10.1016/j.tate.2016.08.015

Ronfeldt, M., Loeb, S., & Wyckoff, J. (2013). How teacher turnover harms student achievement. *American Educational Research Journal, 50*(1), 4-36. https://doi.org/10.3102/0002831212463813

Ronfeldt, M., & McQueen, K. (2017). Does new teacher induction really improve retention? *Journal of Teacher Education, 68*(4), 394-410. https://doi.org/10.1177/0022487117702583

Rosenberg, J. M., Reid, J. W., Dyer, E. B., Koehler, M. J., Fischer, C., & McKenna, T. J. (2020). Idle chatter or compelling conversation? The potential of the social media‐based# NGSSchat network for supporting science education reform efforts. *Journal of Research in Science Teaching, 57*(9), 1322-1355. https://doi.org/10.1002/tea.21660

Saldaña, J. (2016). *The coding manual for qualitative researchers* (3rd ed.). SAGE.

Sawyer, A., Dick, L., Shapiro, E., & Wismer, T. (2019). The top 500 mathematics pins: An analysis of elementary mathematics activities on Pinterest. *Journal of Technology and Teacher Education, 27*(2), 235-263. https://www.learntechlib.org/p/208241/

Schroeder, S., Curcio, R., & Lundgren, L. (2019). Expanding the learning network: How teachers use Pinterest. *Journal of Research on Technology in Education, 51*(2), 166-186. https://doi.org/10.1080/15391523.2019.1573354

Seitz, S. (2016). Pixilated partnerships, overcoming obstacles in qualitative interviews via Skype: A research note. *Qualitative Research, 16*(2), 229-235. https://doi.org/10.1177/1468794115577011

Selwyn, N., Nemorin, S., & Johnson, N. (2017). High-tech, hard work: An investigation of teachers’ work in the digital age. *Learning, Media and Technology, 42*, 390-405. https://doi.org/10.1080/17439884.2016.1252770

Shelton, C. C., & Archambault, L. M. (2019). Who are online teacherpreneurs and what do they do? A survey of content creators on TeachersPayTeachers.com. *Journal of Research on Technology in Education, 51*, 398-414. https://doi.org/10.1080/15391523.2019.1666757

Singletary, T. J., & Anderson, H. (1995) Computer mediated teacher induction. In Z. L. Berge & M. P. Collins (Eds.), *Computer-mediated communication and the online classroom* (Vol. 1: Overview and perspectives). Hampton Press.

Smith Risser, H. (2013). Virtual induction: A novice teacher’s use of Twitter to form an informal mentoring network. *Teaching and Teacher Education, 35*, 25–33. https://doi.org/10.1016/j.tate.2013.05.001

Stanulis, R. N., & Floden, R. E. (2009). Intensive mentoring as a way to help beginning teachers develop balanced instruction. *Journal of Teacher Education, 60*(2), 112-122. https://doi.org/10.1177/0022487108330553

Stanulis, R. N., Little, S., & Wibbens, E. (2012). Intensive mentoring that contributes to change in beginning elementary teachers’ learning to lead classroom discussions. *Teaching and Teacher Education, 28*(1), 32-43. https://doi.org/10.1016/j.tate.2011.08.007

Staudt Willet, K. B. (2019). Revisiting how and why educators use Twitter: Tweet types and purposes in #Edchat. *Journal of Research on Technology in Education, 51*, 273-289. https://doi.org/10.1080/15391523.2019.1611507

Staudt Willet, K. B., & Carpenter, J. P. (2020). Teachers on Reddit? Exploring contributions and interactions in four teaching-related subreddits. *Journal of Research on Technology in Education, 52*, 216-233. https://doi.org/10.1080/15391523.2020.1722978

Staudt Willet, K. B., & Carpenter, J. P. (2021). A tale of two subreddits: Change and continuity in teaching-related online spaces. *British Journal of Educational Technology, 52*(2), 714-733. https://doi.org/10.1111/bjet.13051

Staudt Willet, K. B., Koehler, M.J., & Greenhalgh, S. P. (2017). A tweet by any other frame: Comparing three theoretical frameworks for studying educator interactions on Twitter. In L. Liu & D. Gibson (Eds.), *Research highlights in technology and teacher education 2017* (pp. 63-70). Association for the Advancement of Computing in Education (AACE). http://www.learntechlib.org/p/180960/

Stevenson, M., Bower, M., Falloon, G., Forbes, A., & Hatzigianni, M. (2019). By design: Professional learning ecologies to develop primary school teachers’ makerspaces pedagogical capabilities. *British Journal of Educational Technology, 50*(3), 1260-1274. https://doi.org/10.1111/bjet.12743

Thomas, L., Tuytens, M., Devos, G., Kelchtermans, G., & Vanderlinde, R. (2019). Beginning teachers’ professional support: A mixed methods social network study. *Teaching and Teacher Education, 83*, 134-147. https://doi.org/10.1016/j.tate.2019.04.008

Thompson, J., Windschitl, M., & Braaten, M. (2013). Developing a theory of ambitious early-career teacher practice. *American Educational Research Journal, 50*, 574–615. https://doi.org/10.3102/0002831213476334

Trust, T. (2012). Professional learning networks designed for teacher learning. *Journal of Digital Learning in Teacher Education, 28*(4), 133-138. https://doi.org/10.1080/21532974.2012.10784693

Trust, T., & Horrocks, B. (2017). “I never feel alone in my classroom”: Teacher professional growth within a blended community of practice. *Professional Development in Education, 43*(4), 645–665. https://doi.org/10.1080/19415257.2016.1233507

Trust, T., Krutka, D. G., & Carpenter, J. P. (2016). “Together we are better”: Professional learning networks for teachers. *Computers & Education, 102*, 15-34. https://doi.org/10.1016/j.compedu.2016.06.007

Trust, T., & Prestridge, S. (2021). The interplay of five elements of influence on educators’ PLN actions. *Teaching and Teacher Education, 97*, 103195. https://doi.org/10.1016/j.tate.2020.103195

Veletsianos, G., Johnson, N., & Belikov, O. (2019). Academics' social media use over time is associated with individual, relational, cultural and political factors. *British Journal of Educational Technology, 50*(4), 1713-1728. https://doi.org/10.1111/bjet.12788

Vogel, E. A., Rose, J. P., Roberts, L. R., & Eckles, K. (2014). Social comparison, social media, and self-esteem. *Psychology of Popular Media Culture, 3*(4), 206–222. https://doi.org/10.1037/ppm0000047

Wray, K. A., & Richmond, G. (2018). Factors shaping the agency of beginning science teachers working in high-poverty schools. *Journal of Science Teacher Education, 29*(8), 785-803. https://doi.org/10.1080/1046560X.2018.1514824

Xing, W., & Gao, F. (2018). Exploring the relationship between online discourse and commitment in Twitter professional learning communities. *Computers & Education, 126*, 388-398. https://doi.org/10.1016/j.compedu.2018.08.010

Yadav, A., Gretter, S., Hambrusch, S., & Sands, P. (2016). Expanding computer science education in schools: Understanding teacher experiences and challenges. *Computer Science Education, 26*(4), 235-254. https://doi.org/10.1080/08993408.2016.1257418

Zhukova, O. (2018). Novice teachers’ concerns, early professional experiences and development: Implications for theory and practice. *Discourse and Communication for Sustainable Education, 9*(1), 100-114. https://doi.org/10.2478/dcse-2018-0008
